### ISSUE TITLE
Le premier paragraphe de la plupart des articles est en gras

### ISSUE THREAD

**Issue by antoinesd** [SCIAM-FR/sciam-fr.github.io#91]
Lorsqu'un article ne dispose pas d'un premier titre de niveau 2 (partie), le premier paragraphe de texte est gras. Lorsqu'il y a un titre de partie comme [ici](https://blog.sciam.fr/2024/03/28/ffm-java22.html), le premier paragraphe est normal.

**Comment by CodeSimcoe** [comment]
Dans `_site/css/output.css` :

```css
.prose :where(#preamble > .sectionbody > .paragraph:first-of-type > p):not(:where([class~="not-prose"],[class~="not-prose"] *)) {
  font-size: 1.25rem !important;
  line-height: 1.7rem !important;
  font-weight: 600 !important;
  margin-bottom: 1.2rem !important;
  color: #384a72 !important;
}
```

Je suis pas expert CSS mais ça semble venir de là.
